### ISSUE TITLE
Expand fin cc with Main Target

### ISSUE THREAD

**Issue by bjggi** [KateFFXI/multictrl#1]
This is some great stuff!

I have a question. I would like to expand functions like  "fin()", "cc()" or "attackon", so it uses the Target from the Window i used the command in, kinda like "SendAllTarget" Addon. 

So if i use command //mc fin, all BRD's /RDM's in the Party are using Dispel on my Target.  Or use //mc attackon, all chars attack my Target.

Or is there already something like this included?

I tried something like this, but getting errors. Im not good at this... Maybe you could help me out.

function fin()
	local player_job = windower.ffxi.get_player()
	local mobid = windower.ffxi.get_mob_by_target('t')
		
	if mobid and mobid.id then
		if player_job.main_job == "BRD" then
			windower.send_command('finale '..mobid.id..'')
		end
	end	
end

**Comment by KateFFXI** [comment]
I could change it for the current targetted mob but right now it's using healbot's assist, but could make sense to do that.
